### ISSUE TITLE
cant send email

### ISSUE THREAD

**Issue by nokapzxackx** [0xffvirus/0x69-Spoofer#1]
![image](https://user-images.githubusercontent.com/70822960/201470905-ad93cad5-0720-477e-b5a0-5b253c758eb9.png)

**Comment by nokapzxackx** [comment]
i think cus your site is down? 
https://0xffvirus.000webhostapp.com/

**Comment by nokapzxackx** [comment]
no emails arrive.

**Comment by 0xffvirus** [comment]
That's Weird, Works perfect for me
but i will check it and try to figure it out.

**Comment by nokapzxackx** [comment]
Can you see why no emails arriving?

**Comment by 0xffvirus** [comment]
some emails go to spam index
check the spam index

**Comment by nokapzxackx** [comment]
@website emails don't arrive, @gmails arrive.

**Comment by 0xffvirus** [comment]
i checked that @hotmail arrives too, Not only gmail
i will test it in most Domains 
thanks for the feedback
